### ISSUE TITLE
ktor-serialization-kotlinx-xml is missing native builds

### ISSUE THREAD

**Issue by 89jd** [danbrough/kotlinxtras#3]
:ktor-serialization-kotlinx-xml only seems to contain JVM

**Comment by danbrough** [comment]
Sorry, I just saw this. I'll take a look.

**Comment by danbrough** [comment]
I see from: https://repo.maven.apache.org/maven2/io/ktor/ that upstream has no native support either.
I assume that's because kotlinx.serialization doesn't support xml yet. 
So you'll have to use some other xml serialization library with the string response.

**Comment by 89jd** [comment]
Yep, you are right.

I ended up using `xmlutil`. Can be closed
